version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bizowie_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bizowie-network

  # Flask Application
  web:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/bizowie_erp
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/backend/__pycache__
    networks:
      - bizowie-network
    command: python run.py

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bizowie-network

  # Nginx for production (optional)
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bizowie-network
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  bizowie-network:
    driver: bridge 